#!/bin/bash

# Choose between

#./mill --no-daemon runMainLocal PreMain "$@"
#./mill --no-daemon runMainBackground PreMain "$@"
#./mill --no-daemon runMain PreMain "$@"

# Style commands need to be run with the -w flag, but are managed
# by the separate script feedletter-style

# A bit (well, very) fragile...

MAINCMD="$0"
FEEDLETTER_DIR="$(dirname $MAINCMD)"
EXECNAME="$(basename $MAINCMD)"

cd "$FEEDLETTER_DIR"

if [[ "$1" == "--secrets" ]]; then
    SUBCMD="$3"
    FIRSTARG="$4"
else
    SUBCMD="$1"
    FIRSTARG="$2"
fi

if [[ "$EXECNAME" == "feedletter" ]]; then
    if [[ "$SUBCMD" == "edit-subscribable" ]]; then  # we need native streams...
        ./mill --no-daemon --ticker=false runMainLocal PreMain "$@"
    elif [[  "$SUBCMD" == "daemon" && "$FIRSTARG" == "--fork" ]]; then
        ./mill --no-daemon --ticker=false runMainDaemon PreMain "$@"
    else
        ./mill --no-daemon --ticker=false runMain PreMain "$@"
    fi
else
    echo "Expected this command to be 'feedletter'."
fi


